// Mesa compartida: unirse, publicar mazos, anotar partidas, escrituras simultáneas.
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
const LIB = new URL("../netlify/lib/", import.meta.url).href; import { join } from "node:path";
const dir = mkdtempSync(join(tmpdir(), "grp-"));
writeFileSync(join(dir, "blobs.mjs"), `const M=new Map(); let n=0; export const race={on:false}; export function getStore(){ return {
  async getWithMetadata(k){ const v=M.get(k); return v?{data:JSON.parse(v.d), etag:v.e}:null; },
  async setJSON(k,val,o){ const v=M.get(k); if (race.on){ race.on=false; M.set(k,{d:JSON.stringify({...JSON.parse(v.d), games:[...JSON.parse(v.d).games, {id:"otro-dispositivo", players:[], by:"x"}]}), e:"e"+(++n)}); }
    const w=M.get(k); if (o.onlyIfNew && w) return {modified:false}; if (o.onlyIfMatch && (!w || w.e!==o.onlyIfMatch)) return {modified:false}; M.set(k,{d:JSON.stringify(val), e:"e"+(++n)}); return {modified:true}; } }; }`);
writeFileSync(join(dir, "group.mjs"), readFileSync(new URL("../netlify/functions/group.mjs", import.meta.url), "utf8").replace("@netlify/blobs", "./blobs.mjs").replace(/\.\.\/lib\//g, LIB));
const fn = (await import(join(dir, "group.mjs"))).default; const blobs = await import(join(dir, "blobs.mjs"));
const id = "b".repeat(64), U = "https://x/api/group?id=" + id;
const post = async b => { const r = await fn(new Request(U, {method:"POST", body: JSON.stringify(b)})); return [r.status, await r.json()]; };
const expect = (name, ok, got) => { if (!ok){ console.error(`FALLA ${name}: ${JSON.stringify(got)}`); process.exit(1); } };
const T = {juan1:"tok-juan-1234567890", pedro2:"tok-pedro-123456789", ana3:"tok-ana-12345678901"};
const as = (mid, b) => post({...b, mid, tok: b.tok || T[mid] || "tok-otro-1234567890"});
expect("sin grupo aún", (await fn(new Request(U))).status === 404, null);
expect("no se puede anotar sin grupo", (await as("juan1", {op:"game", game:{}}))[0] === 404, null);
expect("unirse a un grupo inexistente no lo crea", (await as("juan1", {op:"join", name:"Juan"}))[0] === 404, null);
let [s, d] = await as("juan1", {op:"create", name:"Juan", group:"Los del jueves"});
expect("crear", s === 200 && d.name === "Los del jueves" && d.members.juan1.name === "Juan" && !("th" in d.members.juan1), d);
expect("el código ya en uso no se recrea", (await as("pedro2", {op:"create", name:"X"}))[0] === 409, null);
[s, d] = await as("pedro2", {op:"join", name:"Pedro"});
expect("unirse", s === 200 && d.name === "Los del jueves", d);
[s] = await post({op:"decks", mid:"juan1", tok:"otra-clave-cualquiera-123", decks:[]});
expect("sin la clave no se actúa por otro", s === 403, s);
[s] = await as("__proto__", {op:"join", name:"x"});
expect("ids reservados", s === 400, s);
[s, d] = await as("juan1", {op:"decks", decks:[{id:"hk01", name:"Tiritones", commanders:["Hakbal"], power:6.8, br:[3,3], salt:53, list:"1 Sol Ring", upd:10}]});
expect("mazos publicados", d.decks["juan1:hk01"].power === 6.8, d.decks);
[s, d] = await as("juan1", {op:"decks", decks:[{id:"hk01", name:"Viejo", power:5, upd:5}]});
expect("un dispositivo atrasado no pisa la versión nueva", d.decks["juan1:hk01"].name === "Tiritones", d.decks);
[s, d] = await as("juan1", {op:"decks", decks:[{id:"zz01", name:"Otro", upd:1}]});
expect("publicar uno no borra los demás", d.decks["juan1:hk01"] && d.decks["juan1:zz01"], d.decks);
[s, d] = await as("juan1", {op:"decks", decks:[], del:["zz01"]});
expect("borrado explícito", !d.decks["juan1:zz01"] && d.decks["juan1:hk01"], d.decks);
[s, d] = await as("pedro2", {op:"decks", decks:[{id:"vj01", name:"Voja", commanders:["Voja"], power:8.2, br:[3,4]}]});
expect("mazos de cada uno", Object.keys(d.decks).length === 2, d.decks);
[s] = await as("intruso", {op:"decks", decks:[]});
expect("un extraño no publica", s === 403, s);
[s] = await as("juan1", {op:"game", game:{id:"g0009", players:[{mid:"juan1", deck:"juan1:hk01", res:"win"}, {mid:"nadie", deck:"x:y", res:"loss"}]}});
expect("jugadores deben ser del grupo", s === 400, s);
blobs.race.on = true;
[s, d] = await as("juan1", {op:"game", game:{id:"g0001", players:[{mid:"juan1", deck:"juan1:hk01", seat:1, res:"win"}, {mid:"pedro2", deck:"pedro2:vj01", seat:2, res:"loss"}], turn:8, how:"combat"}});
expect("escritura simultánea: no se pierde la otra partida", s === 200 && d.games.map(g=>g.id).sort().join() === "g0001,otro-dispositivo", d.games);
[s] = await as("pedro2", {op:"game", game:{id:"g0001", players:[{mid:"juan1", deck:"juan1:hk01", res:"loss"}, {mid:"pedro2", deck:"pedro2:vj01", res:"win"}]}});
expect("no se sobrescribe la partida de otro", s === 409, s);
[s, d] = await as("ana3", {op:"join", name:"Ana"});
[s] = await as("ana3", {op:"delgame", gid:"g0001"});
expect("quien no jugó no la borra", s === 403, s);
[s, d] = await as("pedro2", {op:"delgame", gid:"g0001"});
expect("un jugador de la partida puede borrarla", !d.games.some(g=>g.id==="g0001"), d.games);
[s] = await fn(new Request(U, {method:"POST", headers:{"sec-fetch-site":"cross-site"}, body:"{}"})).then(r=>[r.status]);
expect("otro sitio no escribe", s === 403, s);
console.log("Grupo OK: crear/unirse, claves por miembro, mazos sin pisarse, partidas validadas y escrituras simultáneas sin pérdidas.");
